buildscript {
    ext.kotlin_version = '1.9.0'
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.1.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

gradle.beforeProject { p ->
    p.ext.flutter = [
        source: '../..',
        compileSdkVersion: 35,
        minSdkVersion: 21,
        targetSdkVersion: 35,
        ndkVersion: "27.0.12077973"
    ]
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
    ext.flutter = [
        source: '../..',
        compileSdkVersion: 35,
        minSdkVersion: 21,
        targetSdkVersion: 35,
        ndkVersion: "27.0.12077973"
    ]
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
    project.ext.flutter = [
        source: '../..',
        compileSdkVersion: 35,
        minSdkVersion: 21,
        targetSdkVersion: 35,
        ndkVersion: "27.0.12077973"
    ]
}

subprojects {
    project.plugins.withId('com.android.library') {
        project.android {
            compileSdkVersion 35
        }
    }
    project.plugins.withId('com.android.application') {
        project.android {
            compileSdkVersion 35
        }
    }
}

subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}