allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}

subprojects {
    project.plugins.withId('com.android.library') {
        project.android {
            compileSdkVersion 35
        }
        try {
            project.android.ext.flutter = [
                compileSdkVersion: 35,
                minSdkVersion: 21,
                targetSdkVersion: 35,
                ndkVersion: "27.0.12077973"
            ]
        } catch (Exception e) {}
    }
    project.plugins.withId('com.android.application') {
        project.android {
            compileSdkVersion 35
        }
        try {
            project.android.ext.flutter = [
                compileSdkVersion: 35,
                minSdkVersion: 21,
                targetSdkVersion: 35,
                ndkVersion: "27.0.12077973"
            ]
        } catch (Exception e) {}
    }
}

subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}