name: sinden_mobile
description: "SI SINDEN - Aplikasi Mobile Detasemen Intelijen Kodaeral V Berbasis Google Material 3 Design"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  provider: ^6.1.2
  http: ^1.2.1
  dio: ^5.4.3+1
  shared_preferences: ^2.2.3
  flutter_local_notifications: ^17.1.2
  geolocator: ^13.0.1
  file_picker: ^8.0.3
  image_picker: ^1.1.1
  intl: ^0.19.0
  google_fonts: ^6.2.1
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/